# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e072c85682a2c55e42ef7190651158a2aa4268f6b92d25a7c861087561a6c535bd98672f45ef155b4f2e328c043bb5c4fcf37bfbb5e87f2b8918da65dd58721b

test:
  secret_key_base: a9973c840ece67a5bebdf6aa6387237f32bbeef2088385ab529069b3d4b02a9ef3dc46e23e5a6dbf3c3c5323fb6612b734a0b025415935ffac75545abc7061b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
